### ISSUE TITLE
Placement of new caching features

### ISSUE THREAD

**Issue by marco-tiloca-sics** [core-wg/groupcomm-bis#11]
The following three items are currently all in draft-ietf-core-groupcomm-bis.

Below the open point on what the most appropriate placement is for each of them.

- General mechanics on cachability of responses at proxies
   --- draft-ietf-core-groupcomm-bis  seems already appropriate
   
- Response validation of individual responses, with the new Multi-ETag option
   --- draft-ietf-core-groupcomm-bis  or separate self-standing document ?

- Response validation of a whole response set cached at the proxy, with the new Group-ETag option
--- draft-tiloca-core-groupcomm-proxy  may be more appropriate

**Comment by EskoDijk** [comment]
As discussed in the IETF 110 CoRE session:
* Multi-ETag could be included in groupcomm-proxy,  or maybe a separate doc
* Group-ETag can be included in groupcomm-proxy
* general mechanics (using existing options) can stay in groupcomm-bis

**Comment by marco-tiloca-sics** [comment]
Trying a further step forward in the same direction, since "general mechanics" above was intended to include also the freshness model for caching.

At the moment, groupcomm-bis covers:

A) Freshness model for caching at endpoints, as just "like in RFC 7252".

B) Freshness model for caching at proxies, i.e. the use of "individual" and "aggregated" cache entries. This is clearly about proxies.

C) Validation model with Multi-ETag. This has to be split into two.
C1) Between origin client and origin servers - This is not really related to the proxy, but, as @chrysn pointed out, the Multi-ETag option uses the same server address encoding as the Response-Forwarding option defined in groupcomm-proxy.
C2) Between proxy (acting as client refreshing its cache) and servers - This is clearly about proxies; it's possible only without end-to-end security between origin client and origin servers.

D) Validation model with Group-ETag -  This is clearly about proxies; it's possible only without end-to-end security between origin client and origin servers.

Then I think we can move (B)(C)(D) to groupcomm-proxy, essentially adding (B) to what proposed in the previous comment. This would expand the scope of groupcomm-proxy, to cover both proxy operations and caching (freshness + validation) for CoAP group communication.

**Comment by chrysn** [comment]
> Then I think we can move (B)(C)(D) to groupcomm-proxy, essentially
> adding (B) to what proposed in the previous comment. This would expand
> the scope of groupcomm-proxy, to cover both proxy operations and
> caching (freshness + validation) for CoAP group communication.

Sounds good to me.

> A) Freshness model for caching at endpoints, as just "like in RFC 7252".

I think that this needs some additional note differentiating between the
freshness of the responses and the freshness of the implicit 4.04ish
from all the other nodes in the group. That latter has a much harder to
specify lifetime. I don't know whether the onus of quantifying this with
a lifetime is to be put on the application ("I'm doing printer
discovery, and it takes at least 5 minutest to set up a printer") or on
the network ("60 seconds for Ethernet"? "10x the beacon interval for some
6los"? "Until I next sniff an MLD packet"? "60 seconds unless
application says otherwise"?).

(From that would then also follow an additional timeout on the
aggregated entry in the proxy).

**Comment by EskoDijk** [comment]
On C1) I don't think that Multi-ETag use (when used without any proxy) is at a proper place in groupcomm-proxy. The fact that the same option-encoding is used is a minor aspect, the topic (i.e. group comm via a proxy) should be the major aspect. So a separate draft would be best. If that's unwanted for some reason, then inclusion in groupcomm-proxy is 2nd best.

@chrysn do you mean server endpoints, that are known to be group members by the client (e.g. due to previous responses, or by configuration) , do not respond to a group request?  This could mean the request or response got lost, or that it led to a suppressed response (like 4.04). I don't think a client can assume anything about freshness for the "missing" responses.  The client can use previous responses that are still fresh according to Max-Age.

**Comment by EskoDijk** [comment]
Ok; I also have some open questions on these different cases, and how a cache in a proxy is supposed to use cached results. This could be a separate new issue for groupcomm-proxy:
* in case cached responses match a new request, does the proxy immediately respond with the cached responses?
* and what if the server does send an updated response later on? (does the proxy forward that as a "second" response to override the previous cached one?)
* or, does the proxy wait until the end of the response-collection period and then augments with potential cached responses from those servers that didn't respond to the latest request?
* or, can the proxy serve a group request from cache without sending any new multicast request out?  (assuming that no further new servers joined the group. In some cases the proxy might know the group members / be notified of new group members. In the general case of no pre-knowledge this probably is not possible.)

**Comment by marco-tiloca-sics** [comment]
> On C1) I don't think that Multi-ETag use (when used without any proxy) is at a proper place in groupcomm-proxy. The fact that the same option-encoding is used is a minor aspect, the topic (i.e. group comm via a proxy) should be the major aspect. So a separate draft would be best. If that's unwanted for some reason, then inclusion in groupcomm-proxy is 2nd best.

At least it seems clear that C1) should not be in groupcomm-bis :-)

Perhaps a separate TBD draft can focus on response validation for (client; origin servers) in group communication, by means of the Multi-ETag option or by using ETag as suggested in https://github.com/core-wg/groupcomm-bis/issues/18 . It seems that both ways have pros and cons.

Then, groupcomm-proxy can build on TBD, to say how that can also be done by a proxy acting as client refreshing its cache, as long as Group OSCORE is not used end-to-end between client and origin servers (see above).

**Comment by EskoDijk** [comment]
That looks like a good dependency graph ;)   if okay to add another document "TBD".
Otherwise it would be an approach to add Multi-ETag to groupcomm-proxy for use through a Proxy; and saying oh by the way you can also use it without a proxy in the path.

**Comment by marco-tiloca-sics** [comment]
> Otherwise it would be an approach to add Multi-ETag to groupcomm-proxy for use through a Proxy; and saying oh by the way you can also use it without a proxy in the path.

Right, although it may be confusing. The main case seems still to be the end-to-end validation between origin client and origin servers, regardless the presence of a proxy. The fact that a proxy can also take advantage of that when it acts as client is more a nice plus.

**Comment by chrysn** [comment]
>  * or, can the proxy serve a group request from cache without sending any new multicast request out?  (assuming that no further new servers joined the group. In some cases the proxy might know the group members / be notified of new group members. In the general case of no pre-knowledge this probably is not possible.)

I think that's the primary use case we should have in mind. The other cases only come to bear if we have good response suppression (granted, that's what much of this work is about), when there's block-wise involved, or when the responses are used later to serve UC requests. (Otherwise, what's the point -- the responses will come through anyway. No gloating points for a proxy that "knew right ahead").

There might not even be an overly long time caching time involved. Think, maybe, of a herd of clients stampeding online after a power outage, all asking around for servers within a few seconds (maybe the first request's response awaiting period is not even over yet). Here a proxy should not forward that stampede but ask once, and if the time that eventually gets determined for for freshness of not-being-on-the-network is just 10 seconds, then that stampede is at least rate limited to one request every 10 seconds (before, eventually, hitting PROBING_RATE).

>  * in case cached responses match a new request, does the proxy immediately respond with the cached responses?
> 
>  * and what if the server does send an updated response later on? (does the proxy forward that as a "second" response to override the previous cached one?)
> 
>  * or, does the proxy wait until the end of the response-collection period and then augments with potential cached responses from those servers that didn't respond to the latest request?

I think we can leave that to the implementation / application, as long as any newer response is sent when it arrives at the proxy. As the latest groupcomm-bis already allows multiple responses from a server, both should work.

If I were to implement it smartly, I'd probably send up to 3 copies of the NON request (one right away, one half-way through and one just in time so that even if the response takes DEFAULT_LEISURE I can still send it on), and send my cached responses after the first lb_leisure has expired. (Or maybe a bit later so that they can be nagled onto any responses from the second request). Although, unless there's pressure to do it smart, I'd do it minimal-effort and that's send-immediately-update-later.

**Comment by marco-tiloca-sics** [comment]
> I think we can leave that to the implementation / application, as long as any newer response is sent when it arrives at the proxy. As the latest groupcomm-bis already allows multiple responses from a server, both should work.
> 
> If I were to implement it smartly, I'd probably send up to 3 copies of the NON request (one right away, one half-way through and one just in time so that even if the response takes DEFAULT_LEISURE I can still send it on), and send my cached responses after the first lb_leisure has expired. (Or maybe a bit later so that they can be nagled onto any responses from the second request). Although, unless there's pressure to do it smart, I'd do it minimal-effort and that's send-immediately-update-later.

Assuming this was all referring to the "aggregated" cache entry, groupcomm-bis is in fact considering the model "send-immediately-update-later".

See https://datatracker.ietf.org/doc/html/draft-ietf-core-groupcomm-bis-03#section-3.4.3, where the "aggregated" cache entry is actually updated only at the end of the collection period, i.e. "After stopping to forward the received responses back to the client ..."

What we should say probably more explicitly is:

- Responses are forwarded back as they come, also in case of multiple responses from a same server. As already mentioned in previous sections, it's ultimately up to the application on the origin client to decide how to handle them.

- During the collection period, if multiple responses from a server come, then each of those responses:

   --- Replaces the previous one from the same server in the list L, that will eventually populate the "aggregated" cache entry at the end of the collection period.

   --- Replaces the previous one in the "individual" cache entry associated to that server.

**Comment by EskoDijk** [comment]
Updated the caching and validation text based on the discussion; see above commit. It seemed not needed to introduce the concept of 'aggregate cache entries' , so I wrote the draft text without these. If needed we can reopen the discussion if the text needs to be improved.
