### ISSUE TITLE
Consider if interaction between Observe and No-Response Options should be described

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/groupcomm-bis#14]
A server receiving an Observe Option in the group request SHOULD respond, and MUST respond even when it adds the client as a new entry to the observers list for that resource.
However, what if the client uses also No-Response? I.e. it might include a weird combination of both options. Should one take precedence over the other?  E.g. an Observe request with suppression of 2.x responses does not make much sense; the server could just decide to not put the client on the observers-list after the first initial processing of the request leads to a 2.x response. 
Or, it could ignore the conflicting No-Response option in this case.

Or, we could say the behaviour is implementation dependent and the client MUST NOT use such particular combinations.

**Comment by marco-tiloca-sics** [comment]
This seems relevant more generally also to non-group requests. Since RFC 7967 does not say so much on this combination,  perhaps it's better to not say more in this document and leave if for coreclarr [1] ? @cabo 

Just for information, we've actually thought a possible usage of a request with both Observe:0 (Register) and No-Response: 2 (Not interested in 2.xx responses). See the last three paragraphs of [2], where this is intentionally phrased just as a suggestion, since it's unclear how much well Observe and No-Response are used together in implementations today.

[1] https://github.com/core-wg/corrclar
[2] https://ace-wg.github.io/ace-key-groupcomm/v-11/draft-ietf-ace-key-groupcomm.html#section-4.1.6.2

**Comment by marco-tiloca-sics** [comment]
As per the commit https://github.com/core-wg/groupcomm-bis/commit/64f51899ecc040a32a4547ea6b86c0614f9cfe35 , responding (suppressing the response) now follows a SHOULD (SHOULD NOT) rather than a MUST (MUST NOT), pointing at the discussion about No-Response in Section 3.1 as an exception to that.

**Comment by EskoDijk** [comment]
Agree, closing.
